package com.zm.api.demo;

import com.zm.util.date.DateUtil;
import com.zm.util.decode.DecodeUtil;

public class CNFDemo {
	public static void main(String[] args) {
		//所开发系统对应的群组机构 建议测试期间用公司的000800010005
		String dataGroup = "000800010005";
		//机器码
		String PCKey="f26a197336060c122438000262173d1a2d3258182c263e102607625c";
		//所在群组名称
		String groupName = "卓瑞信息";
		//业务系统名称 自行修改
		String sysName = "流程控制";
		//基础库名称
		String basedb ="easyflowbasedb";
		//业务库名称
		String businessdb ="easyflow";
		//授权账号
		String apiKey = "key201902280001";
		//授权密码
		String apiPSW = "jorymmmqeye";
		//授权设备数可以不管
		int deviceNum = 50;
		//是否云服务端 默认为false 除非是云服务本机部署
		boolean isServer = false;
		//是否微信服务端
		boolean WXServer = false;
		//初始化基础数据
    	InitBaseSysCnf(dataGroup,sysName,basedb,businessdb,isServer,WXServer);
    	//初始化系统业务数据
    	InitSysCnf(dataGroup,sysName,basedb,businessdb,isServer,apiKey,apiPSW,WXServer);
    	//创建许可证 一定要将下面方法生产的License放入配置文件否则可能因为datagroup不同系统无法解析你的配置文件
		creatLicense(dataGroup,PCKey,deviceNum,groupName);
		System.out.println(DecodeUtil.Decrypt("726a708a0f34081928782b4b35277950"));
	}

	private static void creatLicense(String dataGroup,String PCKey,int deviceNum,String groupName) {
		// TODO Auto-generated method stub
		System.out.println("#设备编码");
		System.out.println(DecodeUtil.CreatePropertiesEncryptKV("PCKey", DecodeUtil.Decrypt(PCKey)));//DecodeUtil.Decrypt("debe709a7437255c7e60744529543f043d2b58027a6a790f3d5e265b")
		System.out.println("#失效期");
		System.out.println(DecodeUtil.CreatePropertiesEncryptKV("usedDate", "2099-12-31 23:59:59"));
		System.out.println("#用户编码");
		System.out.println(DecodeUtil.CreatePropertiesEncryptKV("uniqueKey", dataGroup));
		System.out.println("#可用设备数");
		System.out.println(DecodeUtil.CreatePropertiesEncryptKV("deviceNum", deviceNum));
		System.out.println("#单位名称");
		System.out.println(DecodeUtil.CreatePropertiesEncryptKV("unName", groupName));
	}

	private static void InitBaseSysCnf(String dataGroup,String groupName, String basedb,String businessdb,boolean isServer,boolean WXServer) {
		// TODO Auto-generated method stub
		System.out.println("-- 初始化系统基础表");
		System.out.println("-- 清空系统相关表格");
		System.out.println("TRUNCATE TABLE `"+basedb+"`.`sys_module`;");
		System.out.println("TRUNCATE TABLE `"+basedb+"`.`sys_platform`;");
		System.out.println("TRUNCATE TABLE `"+basedb+"`.`sys_resource`;");
		System.out.println("TRUNCATE TABLE `"+basedb+"`.`sys_datagroup`;");
		System.out.println("TRUNCATE TABLE `"+basedb+"`.`sys_resource`;");
		System.out.println("TRUNCATE TABLE `"+basedb+"`.`sys_role`;");
		System.out.println("TRUNCATE TABLE `"+basedb+"`.`sys_roleresource`;");
		System.out.println("TRUNCATE TABLE `"+basedb+"`.`sys_user`;");
		System.out.println("TRUNCATE TABLE `"+basedb+"`.`sys_userrole`;");
		System.out.println("TRUNCATE TABLE `"+basedb+"`.`sys_unit`;");
		System.out.println("-- 初始化基础业务系统");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_platform` (`platformcode`, `platformname`, `platformsname`, `platformalias`, `platformicon`, `platformoper`, `platformstate`, `platformurl`, `platformdecript`, `platformorder`, `defaulturl`, `datagroup`, `platformdomain`, `iconname`) VALUES('P_0099','管理中心','配置','MQ-System','ios-settings','superadmin','1','','管理中心','99','','"+dataGroup+"','/MQ-System-home','ios-settings');");
		System.out.println("-- 初始化基础级别系统资源");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_resource` (`indexno`, `treeid`, `pid`, `name`, `path`, `title`, `sysname`, `hideInMenu`, `hideInBread`, `notCache`, `showAlways`, `redirect`, `component`, `datagroup`, `platcode`, `icon`, `location`, `clazz`, `method`, `enabled`) values('resource0001','0001','0','systemConfig','/systemConfig','系统管理','MQ-System','0','0','0','1','/systemConfig/userinfo','parentview','"+dataGroup+"','P_0099','ios-settings','0','','','1');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_resource` (`indexno`, `treeid`, `pid`, `name`, `path`, `title`, `sysname`, `hideInMenu`, `hideInBread`, `notCache`, `showAlways`, `redirect`, `component`, `datagroup`, `platcode`, `icon`, `location`, `clazz`, `method`, `enabled`) values('resource00010002','00010001','0001','userManager','/userManager','用户管理','MQ-System','0','0','0','1','/userManager/userList','parentview','"+dataGroup+"','P_0099','ios-people','0','','','1');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_resource` (`indexno`, `treeid`, `pid`, `name`, `path`, `title`, `sysname`, `hideInMenu`, `hideInBread`, `notCache`, `showAlways`, `redirect`, `component`, `datagroup`, `platcode`, `icon`, `location`, `clazz`, `method`, `enabled`) values('resource000100020001','000100010001','00010001','userList','/userList','用户列表','MQ-System','0','0','0','0','','userList','"+dataGroup+"','P_0099','ios-people','0','','','1');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_resource` (`indexno`, `treeid`, `pid`, `name`, `path`, `title`, `sysname`, `hideInMenu`, `hideInBread`, `notCache`, `showAlways`, `redirect`, `component`, `datagroup`, `platcode`, `icon`, `location`, `clazz`, `method`, `enabled`) values('resource00010003','00010005','0001','roleList','/roleList','角色管理','MQ-System','0','0','0','0','','roleList','"+dataGroup+"','P_0099','ios-contacts','4','','','1');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_resource` (`indexno`, `treeid`, `pid`, `name`, `path`, `title`, `sysname`, `hideInMenu`, `hideInBread`, `notCache`, `showAlways`, `redirect`, `component`, `datagroup`, `platcode`, `icon`, `location`, `clazz`, `method`, `enabled`) values('resource00010004','00010004','0001','resourceList','/resourceList','系统资源','MQ-System','0','0','0','0','','resourceList','"+dataGroup+"','P_0099','ios-albums','3','','','1');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_resource` (`indexno`, `treeid`, `pid`, `name`, `path`, `title`, `sysname`, `hideInMenu`, `hideInBread`, `notCache`, `showAlways`, `redirect`, `component`, `datagroup`, `platcode`, `icon`, `location`, `clazz`, `method`, `enabled`) values('resource000100060001','00010006','0001','userinfo','/userinfo','个人信息','MQ-System','0','0','0','0','','userinfo','"+dataGroup+"','P_0099','ios-contact','5','','','1');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_resource` (`indexno`, `treeid`, `pid`, `name`, `path`, `title`, `sysname`, `hideInMenu`, `hideInBread`, `notCache`, `showAlways`, `redirect`, `component`, `datagroup`, `platcode`, `icon`, `location`, `clazz`, `method`, `enabled`) values('resource000100060003','00010007','0001','updatepsw','/updatepsw','更改密码','MQ-System','0','0','0','0','','updatepsw','"+dataGroup+"','P_0099','ios-lock','6','','','1');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_resource` (`indexno`, `treeid`, `pid`, `name`, `path`, `title`, `sysname`, `hideInMenu`, `hideInBread`, `notCache`, `showAlways`, `redirect`, `component`, `datagroup`, `platcode`, `icon`, `location`, `clazz`, `method`, `enabled`) values('resource202005250001','00010003','0001','platformList','/platformList','平台管理','MQ-System','0','0','0','0','','platformList','"+dataGroup+"','P_0099','ios-grid','2','','','1');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_resource` (`indexno`, `treeid`, `pid`, `name`, `path`, `title`, `sysname`, `hideInMenu`, `hideInBread`, `notCache`, `showAlways`, `redirect`, `component`, `datagroup`, `platcode`, `icon`, `location`, `clazz`, `method`, `enabled`) values('resource202005270001','00010002','0001','unitList','/unitList','组织机构','MQ-System','0','0','0','0','','unitList','"+dataGroup+"','P_0099','iacfont iacfont_tuoputu','1','','','1');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_resource` (`indexno`, `treeid`, `pid`, `name`, `path`, `title`, `sysname`, `hideInMenu`, `hideInBread`, `notCache`, `showAlways`, `redirect`, `component`, `datagroup`, `platcode`, `icon`, `location`, `clazz`, `method`, `enabled`) values('resource202006280001','00010008','0001','moduleList','/moduleList','模块管理','MQ-System','0','0','0','0','','moduleList','"+dataGroup+"','P_0099','ios-settings','7','','','1');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_resource` (`indexno`, `treeid`, `pid`, `name`, `path`, `title`, `sysname`, `hideInMenu`, `hideInBread`, `notCache`, `showAlways`, `redirect`, `component`, `datagroup`, `platcode`, `icon`, `location`, `clazz`, `method`, `enabled`) values('resource202006280002','00010009','0001','codetools','/codetools','开发工具','MQ-System','0','0','0','1','/codetools/codeMake','parentview','"+dataGroup+"','P_0099','iacfont iacfont_baoxiu','8','','','1');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_resource` (`indexno`, `treeid`, `pid`, `name`, `path`, `title`, `sysname`, `hideInMenu`, `hideInBread`, `notCache`, `showAlways`, `redirect`, `component`, `datagroup`, `platcode`, `icon`, `location`, `clazz`, `method`, `enabled`) values('resource202006280003','000100090001','00010009','codeMake','/codeMake','代码生成','MQ-System','0','0','0','0','','codeMake','"+dataGroup+"','P_0099','ios-settings','0','','','1');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_resource` (`indexno`, `treeid`, `pid`, `name`, `path`, `title`, `sysname`, `hideInMenu`, `hideInBread`, `notCache`, `showAlways`, `redirect`, `component`, `datagroup`, `platcode`, `icon`, `location`, `clazz`, `method`, `enabled`) values('resource202006290001','00010012','0001','positionList','/positionList','职务管理','MQ-System','0','0','0','0','','positionList','"+dataGroup+"','P_0099','iacfont iacfont_zaiduban','11','','','1');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_resource` (`indexno`, `treeid`, `pid`, `name`, `path`, `title`, `sysname`, `hideInMenu`, `hideInBread`, `notCache`, `showAlways`, `redirect`, `component`, `datagroup`, `platcode`, `icon`, `location`, `clazz`, `method`, `enabled`) values('resource202007040002','00010014','0001','safeLogs','/safeLogs','安全日志','MQ-System','0','0','0','1','','parentview','"+dataGroup+"','P_0099','iacfont iacfont_suo','13','','','1');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_resource` (`indexno`, `treeid`, `pid`, `name`, `path`, `title`, `sysname`, `hideInMenu`, `hideInBread`, `notCache`, `showAlways`, `redirect`, `component`, `datagroup`, `platcode`, `icon`, `location`, `clazz`, `method`, `enabled`) values('resource202007040003','000100140001','00010014','sysLogs','/sysLogs','系统日志','MQ-System','0','0','0','0','','sysLogs','"+dataGroup+"','P_0099','iacfont iacfont_caozuorizhi','0','','','1');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_resource` (`indexno`, `treeid`, `pid`, `name`, `path`, `title`, `sysname`, `hideInMenu`, `hideInBread`, `notCache`, `showAlways`, `redirect`, `component`, `datagroup`, `platcode`, `icon`, `location`, `clazz`, `method`, `enabled`) values('resource202007040004','000100140002','00010014','onLineMonitor','/onLineMonitor','在线用户','MQ-System','0','0','0','0','','onlineMonitor','"+dataGroup+"','P_0099','iacfont iacfont_kaishiduban','1','','','1');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_resource` (`indexno`, `treeid`, `pid`, `name`, `path`, `title`, `sysname`, `hideInMenu`, `hideInBread`, `notCache`, `showAlways`, `redirect`, `component`, `datagroup`, `platcode`, `icon`, `location`, `clazz`, `method`, `enabled`) values('resource202007040005','000100140003','00010014','accessControl','/accessControl','ACL配置','MQ-System','0','0','0','0','','accessControl','"+dataGroup+"','P_0099','iacfont iacfont_aislogo','2','','','1');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_resource` (`indexno`, `treeid`, `pid`, `name`, `path`, `title`, `sysname`, `hideInMenu`, `hideInBread`, `notCache`, `showAlways`, `redirect`, `component`, `datagroup`, `platcode`, `icon`, `location`, `clazz`, `method`, `enabled`) values('resource202009170001','00010015','0001','interfaceManager','/interfaceManager','接口管理','MQ-System','0','0','0','0','','interfaceManager','"+dataGroup+"','P_0099','iacfont_gonglve','14','','','1');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_resource` (`indexno`, `treeid`, `pid`, `name`, `path`, `title`, `sysname`, `hideInMenu`, `hideInBread`, `notCache`, `showAlways`, `redirect`, `component`, `datagroup`, `platcode`, `icon`, `location`, `clazz`, `method`, `enabled`) values('resource202009170002','00010016','0001','functionManager','/functionManager','方法管理','MQ-System','0','0','0','0','','functionManager','"+dataGroup+"','P_0099','iacfont_tongzhi','15','','','1');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_resource` (`indexno`, `treeid`, `pid`, `name`, `path`, `title`, `sysname`, `hideInMenu`, `hideInBread`, `notCache`, `showAlways`, `redirect`, `component`, `datagroup`, `platcode`, `icon`, `location`, `clazz`, `method`, `enabled`) values('resource202010270001','00010017','0001','Codeset','/Codeset','代码集管理','MQ-System','0','0','0','0','','parentview','"+dataGroup+"','P_0099','iacfont_shujuku','16','','','1');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_resource` (`indexno`, `treeid`, `pid`, `name`, `path`, `title`, `sysname`, `hideInMenu`, `hideInBread`, `notCache`, `showAlways`, `redirect`, `component`, `datagroup`, `platcode`, `icon`, `location`, `clazz`, `method`, `enabled`) values('resource202010270002','000100170001','00010017','codeSetClassify','/codeSetClassify','代码集分类','MQ-System','0','0','0','0','','codeSetClassify','"+dataGroup+"','P_0099','iacfont_shujuku','0','','','1');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_resource` (`indexno`, `treeid`, `pid`, `name`, `path`, `title`, `sysname`, `hideInMenu`, `hideInBread`, `notCache`, `showAlways`, `redirect`, `component`, `datagroup`, `platcode`, `icon`, `location`, `clazz`, `method`, `enabled`) values('resource202010270003','000100170002','00010017','codeSet','/codeSet','代码集','MQ-System','0','0','0','0','','codeSet','"+dataGroup+"','P_0099','iacfont_shujuku','1','','','1');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_resource` (`indexno`, `treeid`, `pid`, `name`, `path`, `title`, `sysname`, `hideInMenu`, `hideInBread`, `notCache`, `showAlways`, `redirect`, `component`, `datagroup`, `platcode`, `icon`, `location`, `clazz`, `method`, `enabled`) values('resource202110300001','000100090002','00010009','ssh','/ssh','SSH端','MQ-System','0','0','0','0','','SSHManager','"+dataGroup+"','P_0099','iacfont_yunweiguanli1','1','','','1');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_resource` (`indexno`, `treeid`, `pid`, `name`, `path`, `title`, `sysname`, `hideInMenu`, `hideInBread`, `notCache`, `showAlways`, `redirect`, `component`, `datagroup`, `platcode`, `icon`, `location`, `clazz`, `method`, `enabled`) values('resource202110300002','000100090003','00010009','influxDBManager','/influxDBManager','时序调试','MQ-System','0','0','0','0','','influxDBManager','"+dataGroup+"','P_0099','iacfont_shujuku','2','','','1');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_resource` (`indexno`, `treeid`, `pid`, `name`, `path`, `title`, `sysname`, `hideInMenu`, `hideInBread`, `notCache`, `showAlways`, `redirect`, `component`, `datagroup`, `platcode`, `icon`, `location`, `clazz`, `method`, `enabled`) VALUES('resource202007040001','00010013','0001','parameter','/parameter','参数配置','MQ-System','0','0','0','0','','parameter','"+dataGroup+"','P_0099','iacfont iacfont_shezhi','12',NULL,NULL,'1');");


		if(isServer) {
			System.out.println("INSERT INTO `"+basedb+"`.`sys_resource` (`indexno`, `treeid`, `pid`, `name`, `path`, `title`, `sysname`, `hideInMenu`, `hideInBread`, `notCache`, `showAlways`, `redirect`, `component`, `datagroup`, `platcode`, `icon`, `location`, `clazz`, `method`, `enabled`) VALUES('resource202006280004','00010010','0001','appManager','/appManager','应用管理','MQ-System','0','0','0','0','','appManager','"+dataGroup+"','P_0099','iacfont iacfont_shoujishangchuan','9',NULL,NULL,'1');");
			System.out.println("INSERT INTO `"+basedb+"`.`sys_resource` (`indexno`, `treeid`, `pid`, `name`, `path`, `title`, `sysname`, `hideInMenu`, `hideInBread`, `notCache`, `showAlways`, `redirect`, `component`, `datagroup`, `platcode`, `icon`, `location`, `clazz`, `method`, `enabled`) VALUES('resource202006280005','00010011','0001','appauthorization','/appauthorization','应用授权','MQ-System','0','0','0','0','','appauthorization','"+dataGroup+"','P_0099','iacfont iacfont_zaiduban','10',NULL,NULL,'1');");
		}
		if(WXServer) {
			System.out.println("INSERT INTO `"+basedb+"`.`sys_resource` (`indexno`, `treeid`, `pid`, `name`, `path`, `title`, `sysname`, `hideInMenu`, `hideInBread`, `notCache`, `showAlways`, `redirect`, `component`, `datagroup`, `platcode`, `icon`, `location`, `clazz`, `method`, `enabled`) VALUES('resource202006290002','0002','0','socialtools','/socialtools','社交配置','MQ-System','0','0','0','1','','parentview','"+dataGroup+"','P_0099','iacfont iacfont_caidan','1',NULL,NULL,'1');");
			System.out.println("INSERT INTO `"+basedb+"`.`sys_resource` (`indexno`, `treeid`, `pid`, `name`, `path`, `title`, `sysname`, `hideInMenu`, `hideInBread`, `notCache`, `showAlways`, `redirect`, `component`, `datagroup`, `platcode`, `icon`, `location`, `clazz`, `method`, `enabled`) VALUES('resource202006290003','00020001','0002','wxcnf','/wxcnf','微信配置','MQ-System','0','0','0','1','','parentview','"+dataGroup+"','P_0099','iacfont iacfont_weixin','0',NULL,NULL,'1');");
			System.out.println("INSERT INTO `"+basedb+"`.`sys_resource` (`indexno`, `treeid`, `pid`, `name`, `path`, `title`, `sysname`, `hideInMenu`, `hideInBread`, `notCache`, `showAlways`, `redirect`, `component`, `datagroup`, `platcode`, `icon`, `location`, `clazz`, `method`, `enabled`) VALUES('resource202007080001','000200010001','00020001','weChatTempList','/weChatTempList','微信模板','MQ-System','0','0','0','0','','weChatTempList','"+dataGroup+"','P_0099','iacfont_fenlei','0',NULL,NULL,'1');");
			System.out.println("INSERT INTO `"+basedb+"`.`sys_resource` (`indexno`, `treeid`, `pid`, `name`, `path`, `title`, `sysname`, `hideInMenu`, `hideInBread`, `notCache`, `showAlways`, `redirect`, `component`, `datagroup`, `platcode`, `icon`, `location`, `clazz`, `method`, `enabled`) VALUES('resource202007080002','000200010002','00020001','weChatParameters','/weChatParameters','参数设置','MQ-System','0','0','0','0','','weChatParameters','"+dataGroup+"','P_0099','iacfont_fenlei','1',NULL,NULL,'1');");
			System.out.println("INSERT INTO `"+basedb+"`.`sys_resource` (`indexno`, `treeid`, `pid`, `name`, `path`, `title`, `sysname`, `hideInMenu`, `hideInBread`, `notCache`, `showAlways`, `redirect`, `component`, `datagroup`, `platcode`, `icon`, `location`, `clazz`, `method`, `enabled`) VALUES('resource202007080003','000200010003','00020001','weChatMenu','/weChatMenu','微信菜单','MQ-System','0','0','0','0','','weChatMenu','"+dataGroup+"','P_0099','iacfont_fenlei','2',NULL,NULL,'1');");
			System.out.println("INSERT INTO `"+basedb+"`.`sys_resource` (`indexno`, `treeid`, `pid`, `name`, `path`, `title`, `sysname`, `hideInMenu`, `hideInBread`, `notCache`, `showAlways`, `redirect`, `component`, `datagroup`, `platcode`, `icon`, `location`, `clazz`, `method`, `enabled`) VALUES('resource202007080004','000200010004','00020001','weChatPush','/weChatPush','微信推送','MQ-System','0','0','0','0','','weChatPush','"+dataGroup+"','P_0099','iacfont_fenlei','3',NULL,NULL,'1');");
			System.out.println("INSERT INTO `"+basedb+"`.`sys_resource` (`indexno`, `treeid`, `pid`, `name`, `path`, `title`, `sysname`, `hideInMenu`, `hideInBread`, `notCache`, `showAlways`, `redirect`, `component`, `datagroup`, `platcode`, `icon`, `location`, `clazz`, `method`, `enabled`) VALUES('resource202007080005','000200010005','00020001','weChatQA','/weChatQA','微信问答','MQ-System','0','0','0','0','','weChatQA','"+dataGroup+"','P_0099','iacfont_fenlei','4',NULL,NULL,'1');");
			System.out.println("INSERT INTO `"+basedb+"`.`sys_resource` (`indexno`, `treeid`, `pid`, `name`, `path`, `title`, `sysname`, `hideInMenu`, `hideInBread`, `notCache`, `showAlways`, `redirect`, `component`, `datagroup`, `platcode`, `icon`, `location`, `clazz`, `method`, `enabled`) VALUES('resource202007080006','000200010006','00020001','weixinAdvertorial','/weixinAdvertorial','微信软文','MQ-System','0','0','0','0','','weixinAdvertorial','"+dataGroup+"','P_0099','iacfont_fenlei','5',NULL,NULL,'1');");
			System.out.println("INSERT INTO `"+basedb+"`.`sys_resource` (`indexno`, `treeid`, `pid`, `name`, `path`, `title`, `sysname`, `hideInMenu`, `hideInBread`, `notCache`, `showAlways`, `redirect`, `component`, `datagroup`, `platcode`, `icon`, `location`, `clazz`, `method`, `enabled`) VALUES('resource202007080007','00020002','0002','messageConfig','/messageConfig','短信管理','MQ-System','0','0','0','1','','parentview','"+dataGroup+"','P_0099','iacfont_tongzhi','1',NULL,NULL,'1');");
			System.out.println("INSERT INTO `"+basedb+"`.`sys_resource` (`indexno`, `treeid`, `pid`, `name`, `path`, `title`, `sysname`, `hideInMenu`, `hideInBread`, `notCache`, `showAlways`, `redirect`, `component`, `datagroup`, `platcode`, `icon`, `location`, `clazz`, `method`, `enabled`) VALUES('resource202007080008','000200020001','00020002','messageTempList','/messageTempList','短信模板','MQ-System','0','0','0','0','','messageTempList','"+dataGroup+"','P_0099','iacfont_fenlei','0',NULL,NULL,'1');");
		}
		
		System.out.println("-- 插入超级管理员角色");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_role` (`roleid`, `name`, `type`, `location`, `descript`, `creater`, `creattime`, `creatunitid`, `datagroup`, `platformcode`) VALUES('0001','超级管理员','0','0','超级管理员','superadmin',NULL,'0001','"+dataGroup+"','');");
		System.out.println("-- 插入超级管理员账号");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_user` (`loginname`, `realname`, `password`, `descript`, `address`, `mobil`, `location`, `lastlogintime`, `lastloginip`, `logincount`, `enabled`, `unittreeid`, `iconname`, `iconurl`, `nickname`, `sex`, `accounttype`, `datagroup`) VALUES('superadmin','超级管理员','576f2da2221d710935131a7541741f23017c540951','超级管理员','超级管理员','','0','2018-10-14 10:42:21','','0','0','0001','','','','1','','"+dataGroup+"');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_user` (`loginname`, `realname`, `password`, `descript`, `address`, `mobil`, `location`, `lastlogintime`, `lastloginip`, `logincount`, `enabled`, `unittreeid`, `iconname`, `iconurl`, `nickname`, `sex`, `accounttype`, `datagroup`) VALUES('admin','管理员','576f2da2221d710935131a7541741f23017c540951','管理员','管理员','','0','2018-10-14 10:42:21','','0','0','0004','','','','1','','"+dataGroup+"');");
		System.out.println("-- 插入超级管理员账号角色");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_userrole` (`loginname`, `roleid`, `optime`, `opter`, `datagroup`) VALUES('superadmin','0001','"+DateUtil.getCurDateTime()+"','superadmin','"+dataGroup+"');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_userrole` (`loginname`, `roleid`, `optime`, `opter`, `datagroup`) VALUES('admin','0004','"+DateUtil.getCurDateTime()+"','superadmin','"+dataGroup+"');");
		System.out.println("-- 插入超级管理员账号额外信息");
		System.out.println("INSERT INTO `"+businessdb+"`.`base_user_extend` VALUES ('superadmin', 'superadmin', '', '', null, null, null, '', '', null, null, null, null, '0', '0', '0', '0', '0', '0', '0', '0', '0', null,'" + dataGroup + "', null, null, null, null, null, null, null, null);");
		System.out.println("INSERT INTO `"+businessdb+"`.`base_user_extend` VALUES ('admin', 'admin', '', '', null, null, null, '', '', null, null, null, null, '0', '0', '0', '0', '0', '0', '0', '0', '0', null,'" + dataGroup + "', null, null, null, null, null, null, null, null);");
		System.out.println("-- 插入可用群组");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_datagroup` (`datagroup`, `groupname`, `groupdes`, `groupstate`, `groupdname`, `creater`, `creattime`, `locationorder`, `bindsysurls`, `odatagroup`, `grouptype`) VALUES('"+dataGroup+"','"+groupName+"','"+groupName+"',1,'localhost','superadmin','"+DateUtil.getCurDateTime()+"',1,'','"+dataGroup+"',1);");
		System.out.println("-- 插入机构信息");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_unit` (`treeid`, `typeid`, `name`, `infotype`, `location`, `descript`, `bindipurl`, `linkadd`, `linktel`, `linkmail`, `linkweb`, `pcode`, `dcode`, `datagroup`) VALUES('0001','0002','系统维护','0','0','系统维护','','','','','','','','"+dataGroup+"');");
		System.out.println("-- 插入系统级别Module信息");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_module` (`indexno`, `modulecode`, `path`, `form`, `scope`, `action`, `defaultPage`, `modulename`, `ordernum`, `linkclass`, `linkpages`, `initmethod`, `authcode`, `creater`, `creattime`, `moduletype`) VALUES('SM2018120014','0014','/api/private/ajax','','','modules.business.AjaxDoBase','','Ajax方法业务级[需要验证登录]','0','','','','','superadmin','2019-03-25 22:39:37','API');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_module` (`indexno`, `modulecode`, `path`, `form`, `scope`, `action`, `defaultPage`, `modulename`, `ordernum`, `linkclass`, `linkpages`, `initmethod`, `authcode`, `creater`, `creattime`, `moduletype`) VALUES('SM2018120015','0015','/api/public/ajax','','','modules.business.sys.pub.AjaxDoPub','public','Ajax方法业务级','0','','','','','superadmin','2019-03-25 22:39:27','API');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_module` (`indexno`, `modulecode`, `path`, `form`, `scope`, `action`, `defaultPage`, `modulename`, `ordernum`, `linkclass`, `linkpages`, `initmethod`, `authcode`, `creater`, `creattime`, `moduletype`) VALUES('SM2018120016','0016','/api/private/sys/ajax','','','com.zm.base.AjaxDoBase','','Ajax方法系统级[需要验证登录]','0','','','','','superadmin','2019-03-25 22:38:58','API');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_module` (`indexno`, `modulecode`, `path`, `form`, `scope`, `action`, `defaultPage`, `modulename`, `ordernum`, `linkclass`, `linkpages`, `initmethod`, `authcode`, `creater`, `creattime`, `moduletype`) VALUES('SM2018120017','0017','/api/public/sys/ajax','','','com.zm.base.pub.AjaxDoPub','public','Ajax方法系统级','0','','','','','superadmin','2019-01-07 20:20:23','API');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_module` (`indexno`, `modulecode`, `path`, `form`, `scope`, `action`, `defaultPage`, `modulename`, `ordernum`, `linkclass`, `linkpages`, `initmethod`, `authcode`, `creater`, `creattime`, `moduletype`) VALUES('SM2018120024','0024','/api/private/sysbase/file','','','com.zm.base.file.FileAction','','文件操作','0','','','','','superadmin','2019-03-25 22:40:40','API');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_module` (`indexno`, `modulecode`, `path`, `form`, `scope`, `action`, `defaultPage`, `modulename`, `ordernum`, `linkclass`, `linkpages`, `initmethod`, `authcode`, `creater`, `creattime`, `moduletype`) VALUES('SM2019050003','0134','/SMS/SUBHook','','','com.zm.msg.sms.SUBHookAction','','短信上行','1','','','','','superadmin','2019-05-21 09:06:15','API');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_module` (`indexno`, `modulecode`, `path`, `form`, `scope`, `action`, `defaultPage`, `modulename`, `ordernum`, `linkclass`, `linkpages`, `initmethod`, `authcode`, `creater`, `creattime`, `moduletype`) VALUES('SM2019110002','0164','/api/private/base','','','modules.base.sys.api.BaseAction','','基础接口（app）  ','1','','','','','superadmin','2019-11-20 11:29:54','API');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_module` (`indexno`, `modulecode`, `path`, `form`, `scope`, `action`, `defaultPage`, `modulename`, `ordernum`, `linkclass`, `linkpages`, `initmethod`, `authcode`, `creater`, `creattime`, `moduletype`) VALUES('SM2020050020','0194','/api/private/sysResource','','','modules.base.sys.api.sysResource.SysResourceAction','','资源管理（api）','1','','','','','superadmin','2020-05-12 11:12:13','API');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_module` (`indexno`, `modulecode`, `path`, `form`, `scope`, `action`, `defaultPage`, `modulename`, `ordernum`, `linkclass`, `linkpages`, `initmethod`, `authcode`, `creater`, `creattime`, `moduletype`) VALUES('SM2020050021','0195','/api/private/sysRole','','','modules.base.sys.api.sys.action.roleAction','','角色管理（api）','1','','','','','superadmin','2020-05-20 10:43:13','API');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_module` (`indexno`, `modulecode`, `path`, `form`, `scope`, `action`, `defaultPage`, `modulename`, `ordernum`, `linkclass`, `linkpages`, `initmethod`, `authcode`, `creater`, `creattime`, `moduletype`) VALUES('SM2020050022','0196','/api/private/sysPlatform','','','modules.base.sys.api.sysPlatform.SysPlatformAction','','平台管理（api）','1','','','','','superadmin','2020-05-20 10:43:13','API');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_module` (`indexno`, `modulecode`, `path`, `form`, `scope`, `action`, `defaultPage`, `modulename`, `ordernum`, `linkclass`, `linkpages`, `initmethod`, `authcode`, `creater`, `creattime`, `moduletype`) VALUES('SM2020050023','0197','/api/private/userList','','','modules.base.sys.api.sys.action.userAction','','用户管理（api）','1','','','','','superadmin','2020-05-20 10:43:13','API');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_module` (`indexno`, `modulecode`, `path`, `form`, `scope`, `action`, `defaultPage`, `modulename`, `ordernum`, `linkclass`, `linkpages`, `initmethod`, `authcode`, `creater`, `creattime`, `moduletype`) VALUES('SM2020050024','0198','/api/private/unitList','','','modules.base.sys.api.sysUnit.SysUnitAction','','组织机构列表(api)','1','','','','','superadmin','2020-05-22 10:43:13','API');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_module` (`indexno`, `modulecode`, `path`, `form`, `scope`, `action`, `defaultPage`, `modulename`, `ordernum`, `linkclass`, `linkpages`, `initmethod`, `authcode`, `creater`, `creattime`, `moduletype`) VALUES('SM2020050027','0201','/api/private/moduleList','','','modules.base.sys.api.mkpz.SysModuleAction','','模块管理（api）','1','','','','','superadmin','2020-05-28 10:43:13','API');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_module` (`indexno`, `modulecode`, `path`, `form`, `scope`, `action`, `defaultPage`, `modulename`, `ordernum`, `linkclass`, `linkpages`, `initmethod`, `authcode`, `creater`, `creattime`, `moduletype`) VALUES('SM2020060001','0034','/api/private/appAuthorization','','','modules.base.sys.api.appmanage.AppAuthorizationAction','','App管理','1','','','','','superadmin','2019-04-12 08:31:53','API');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_module` (`indexno`, `modulecode`, `path`, `form`, `scope`, `action`, `defaultPage`, `modulename`, `ordernum`, `linkclass`, `linkpages`, `initmethod`, `authcode`, `creater`, `creattime`, `moduletype`) VALUES('SM2020010012','1243','/api/private/system/code/codeCreate','','','modules.business.sys.codemaker.CodeToolsAction','','代码生成','1','','','','','superadmin','2019-04-12 08:31:53','API');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_module` (`indexno`, `modulecode`, `path`, `form`, `scope`, `action`, `defaultPage`, `modulename`, `ordernum`, `linkclass`, `linkpages`, `initmethod`, `authcode`, `creater`, `creattime`, `moduletype`) VALUES('SM2020010009','1240','/api/private/systemSetting/APPManage','','','modules.base.sys.api.appmanage.BusinessAppAction','','APP管理接口','0','','','','','superadmin','2020-01-15 11:25:40','API');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_module` (`indexno`, `modulecode`, `path`, `form`, `scope`, `action`, `defaultPage`, `modulename`, `ordernum`, `linkclass`, `linkpages`, `initmethod`, `authcode`, `creater`, `creattime`, `moduletype`) VALUES('SM2020010010','1241','/api/private/systemSetting/positioncnf','','','modules.base.sys.api.positionmanage.SysPositionAction','','职务管理接口','0','','','','','superadmin','2020-01-16 16:22:42','API');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_module` (`indexno`, `modulecode`, `path`, `form`, `scope`, `action`, `defaultPage`, `modulename`, `ordernum`, `linkclass`, `linkpages`, `initmethod`, `authcode`, `creater`, `creattime`, `moduletype`) VALUES('SM2020060002','1244','/api/private/test','','','modules.business.sys.TestAction','','测试模块','1','','','','','superadmin','2020-06-30 19:31:36','API');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_module` (`indexno`, `modulecode`, `path`, `form`, `scope`, `action`, `defaultPage`, `modulename`, `ordernum`, `linkclass`, `linkpages`, `initmethod`, `authcode`, `creater`, `creattime`, `moduletype`) VALUES('SM2020070001','1245','/api/private/systemSetting/sysConfig','','','modules.base.sys.api.syscnf.sysConfigAction','','参数配置','1','','','','','superadmin','2020-07-04 10:09:22','API');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_module` (`indexno`, `modulecode`, `path`, `form`, `scope`, `action`, `defaultPage`, `modulename`, `ordernum`, `linkclass`, `linkpages`, `initmethod`, `authcode`, `creater`, `creattime`, `moduletype`) VALUES('SM2020070002','1246','/api/private/sys/safety/safetyManager','','','modules.base.sys.api.sys.action.safetyAction','','安全日志','1','','','','','superadmin','2020-07-06 16:54:02','API');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_module` (`indexno`, `modulecode`, `path`, `form`, `scope`, `action`, `defaultPage`, `modulename`, `ordernum`, `linkclass`, `linkpages`, `initmethod`, `authcode`, `creater`, `creattime`, `moduletype`) VALUES('SM2020070003','1247','/api/private/common','','','modules.base.sys.api.sys.action.CommAction','','共用模块','1','','','','','superadmin','2020-07-07 08:04:03','API');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_module` (`indexno`, `modulecode`, `path`, `form`, `scope`, `action`, `defaultPage`, `modulename`, `ordernum`, `linkclass`, `linkpages`, `initmethod`, `authcode`, `creater`, `creattime`, `moduletype`) VALUES('SM2020070051','1295','/api/private/baseapi','','','modules.business.base.action.BaseAction','','基础接口（api）  ','1','','','','','superadmin','2020-07-13 14:40:24','API');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_module` (`indexno`, `modulecode`, `path`, `form`, `scope`, `action`, `defaultPage`, `modulename`, `ordernum`, `linkclass`, `linkpages`, `initmethod`, `authcode`, `creater`, `creattime`, `moduletype`) VALUES('SM2020090066','1310','/api/private/functionManager','','','modules.business.sys.interfacemanager.action.BaseFunctionListAction','','方法管理','1','','','','','superadmin','2020-09-17 09:33:51','API');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_module` (`indexno`, `modulecode`, `path`, `form`, `scope`, `action`, `defaultPage`, `modulename`, `ordernum`, `linkclass`, `linkpages`, `initmethod`, `authcode`, `creater`, `creattime`, `moduletype`) VALUES('SM2020090003','1311','/api/interfaceManager','','','modules.business.sys.interfacemanager.action.BaseInterfaceListAction','','接口管理','1','','','','','superadmin','2020-09-17 09:33:51','API');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_module` (`indexno`, `modulecode`, `path`, `form`, `scope`, `action`, `defaultPage`, `modulename`, `ordernum`, `linkclass`, `linkpages`, `initmethod`, `authcode`, `creater`, `creattime`, `moduletype`) VALUES('SM2020090067','1312','/api/private/document','','','modules.business.oa.document.action.Document_manager_interface','','文件仓库管理','1','','','','','superadmin','2020-09-23 11:37:07','API');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_module` (`indexno`, `modulecode`, `path`, `form`, `scope`, `action`, `defaultPage`, `modulename`, `ordernum`, `linkclass`, `linkpages`, `initmethod`, `authcode`, `creater`, `creattime`, `moduletype`) VALUES('SM2020100006','1319','/api/private/base/action/codeSetClassify','','','modules.business.base.action.BaseCodeSetClassifyAction','','代码集配置-代码集分类','1','','','','','superadmin','2020-10-27 15:29:28','API');");
		System.out.println("INSERT INTO `"+basedb+"`.`sys_module` (`indexno`, `modulecode`, `path`, `form`, `scope`, `action`, `defaultPage`, `modulename`, `ordernum`, `linkclass`, `linkpages`, `initmethod`, `authcode`, `creater`, `creattime`, `moduletype`) VALUES('SM2020100007','1320','/api/private/base/action/codeSet','','','modules.business.base.action.BaseCodeSetAction','','代码集配置-代码集','1','','','','','superadmin','2020-10-27 16:46:24','API');");
		if(isServer) {
			System.out.println("INSERT INTO `"+basedb+"`.`sys_module` (`indexno`, `modulecode`, `path`, `form`, `scope`, `action`, `defaultPage`, `modulename`, `ordernum`, `linkclass`, `linkpages`, `initmethod`, `authcode`, `creater`, `creattime`, `moduletype`) VALUES('SM2021050001','1325','/private/cloudserver/api','','','com.zm.interfaze.cloud.server.InterfazeOpAction','public','云接口','1','','','','','superadmin','2021-04-13 11:32:46','API');");
			System.out.println("INSERT INTO `"+basedb+"`.`sys_module` (`indexno`, `modulecode`, `path`, `form`, `scope`, `action`, `defaultPage`, `modulename`, `ordernum`, `linkclass`, `linkpages`, `initmethod`, `authcode`, `creater`, `creattime`, `moduletype`) VALUES('SM2021040001','1324','/private/wx/api','','','com.zm.base.wx.action.WeixinBaseOPAction','public','微信接口','1','','','','','superadmin','2021-04-13 11:32:46','API');");
		}
		
		if(isServer||WXServer) {
			System.out.println("INSERT INTO `"+basedb+"`.`sys_module` (`indexno`, `modulecode`, `path`, `form`, `scope`, `action`, `defaultPage`, `modulename`, `ordernum`, `linkclass`, `linkpages`, `initmethod`, `authcode`, `creater`, `creattime`, `moduletype`) VALUES('SM2020070018','1262','/api/private/weChatConfig','','','com.zm.base.wx.action.WXConfigInterface','','微信管理（api）','1','','','','','superadmin','2020-07-08 14:30:24','API');");
			System.out.println("INSERT INTO `"+basedb+"`.`sys_module` (`indexno`, `modulecode`, `path`, `form`, `scope`, `action`, `defaultPage`, `modulename`, `ordernum`, `linkclass`, `linkpages`, `initmethod`, `authcode`, `creater`, `creattime`, `moduletype`) VALUES('SM2020070019','1263','/api/private/messageConfig','','','com.zm.base.sms.action.MsgConfigInterface','','短信管理（api）','1','','','','','superadmin','2020-07-08 18:30:24','API');");
			System.out.println("INSERT INTO `"+basedb+"`.`sys_module` (`indexno`, `modulecode`, `path`, `form`, `scope`, `action`, `defaultPage`, `modulename`, `ordernum`, `linkclass`, `linkpages`, `initmethod`, `authcode`, `creater`, `creattime`, `moduletype`) VALUES('SM2021090001','1326','/api/public/advertorial','','','com.zm.base.wx.action.WeixinPublicAction','public','软文相关操作','1','','','','','superadmin','2021-09-27 21:59:49','API');");
		}
	}
	
	private static void InitSysCnf(String dataGroup,String groupName,String basedb,String businessdb,boolean isServer,String apiKey,String apiPSW,boolean WXServer) {
		// TODO Auto-generated method stub
		System.out.println("-- 初始化业务系统配置信息");
    	System.out.println("TRUNCATE TABLE `"+businessdb+"`.`base_sys_cnf`;");
    	System.out.println("INSERT INTO `"+businessdb+"`.`base_sys_cnf`(`PKEY`, `PVAL`, `ENCRYPT`, `ENCRYPTCODE`, `STATE`, `UPDATETIME`, `CNFPARAMSDES`, `MODULENAME`, `MODULCODE`) VALUES ('APIADRESS', '"+DecodeUtil.EncryptBase64("https://api.iacyun.com/private/cloudserver/api.data", dataGroup, true)+"', 1, '', 1, '2020-12-17 10:22:23', '云端默认连接', '云台配置', '0003');");
    	System.out.println("INSERT INTO `"+businessdb+"`.`base_sys_cnf`(`PKEY`, `PVAL`, `ENCRYPT`, `ENCRYPTCODE`, `STATE`, `UPDATETIME`, `CNFPARAMSDES`, `MODULENAME`, `MODULCODE`) VALUES ('ATWXUSER', '"+DecodeUtil.EncryptBase64("1", dataGroup, true)+"', 1, '', 1, '2020-12-17 10:22:23', '微信用户自动创建', '系统配置', '0000');");
    	System.out.println("INSERT INTO `"+businessdb+"`.`base_sys_cnf`(`PKEY`, `PVAL`, `ENCRYPT`, `ENCRYPTCODE`, `STATE`, `UPDATETIME`, `CNFPARAMSDES`, `MODULENAME`, `MODULCODE`) VALUES ('BASEDBNAME', '"+DecodeUtil.EncryptBase64(basedb.toUpperCase(), dataGroup, true)+"', 1, '', 1, '2020-12-17 10:22:23', '系统数据库', '系统配置', '0000');");
    	System.out.println("INSERT INTO `"+businessdb+"`.`base_sys_cnf`(`PKEY`, `PVAL`, `ENCRYPT`, `ENCRYPTCODE`, `STATE`, `UPDATETIME`, `CNFPARAMSDES`, `MODULENAME`, `MODULCODE`) VALUES ('BASEDIR', '"+DecodeUtil.EncryptBase64("/home/logs", dataGroup, true)+"', 1, '', 1, '2020-12-17 10:22:23', '日志根目录', 'Logg配置', '0002');");
    	System.out.println("INSERT INTO `"+businessdb+"`.`base_sys_cnf`(`PKEY`, `PVAL`, `ENCRYPT`, `ENCRYPTCODE`, `STATE`, `UPDATETIME`, `CNFPARAMSDES`, `MODULENAME`, `MODULCODE`) VALUES ('CLOUDKEY', '"+DecodeUtil.EncryptBase64(apiKey, dataGroup, true)+"', 1, '', 1, '2020-12-17 10:22:23', '云端账号', '云台配置', '0003');");
    	System.out.println("INSERT INTO `"+businessdb+"`.`base_sys_cnf`(`PKEY`, `PVAL`, `ENCRYPT`, `ENCRYPTCODE`, `STATE`, `UPDATETIME`, `CNFPARAMSDES`, `MODULENAME`, `MODULCODE`) VALUES ('CLOUDPASS', '"+DecodeUtil.EncryptBase64(apiPSW, dataGroup, true)+"', 1, '', 1, '2020-12-17 10:22:23', '云端密码', '云台配置', '0003');");
    	System.out.println("INSERT INTO `"+businessdb+"`.`base_sys_cnf`(`PKEY`, `PVAL`, `ENCRYPT`, `ENCRYPTCODE`, `STATE`, `UPDATETIME`, `CNFPARAMSDES`, `MODULENAME`, `MODULCODE`) VALUES ('CONSOLELOGPATH', '"+DecodeUtil.EncryptBase64("console", dataGroup, true)+"', 1, '', 1, '2020-12-17 10:22:23', '信息日志目录', 'Logg配置', '0002');");
    	System.out.println("INSERT INTO `"+businessdb+"`.`base_sys_cnf`(`PKEY`, `PVAL`, `ENCRYPT`, `ENCRYPTCODE`, `STATE`, `UPDATETIME`, `CNFPARAMSDES`, `MODULENAME`, `MODULCODE`) VALUES ('DBBAK', '"+DecodeUtil.EncryptBase64("1", dataGroup, true)+"', 1, '', 1, '2020-12-17 10:22:23', '是否备份数据库', '系统配置', '0000');");
    	System.out.println("INSERT INTO `"+businessdb+"`.`base_sys_cnf`(`PKEY`, `PVAL`, `ENCRYPT`, `ENCRYPTCODE`, `STATE`, `UPDATETIME`, `CNFPARAMSDES`, `MODULENAME`, `MODULCODE`) VALUES ('DEBUG', '"+DecodeUtil.EncryptBase64("1", dataGroup, true)+"', 1, '', 1, '2020-12-17 10:22:23', 'Debug开启模式', 'Debug配置', '0001');");
    	System.out.println("INSERT INTO `"+businessdb+"`.`base_sys_cnf`(`PKEY`, `PVAL`, `ENCRYPT`, `ENCRYPTCODE`, `STATE`, `UPDATETIME`, `CNFPARAMSDES`, `MODULENAME`, `MODULCODE`) VALUES ('DEBUGLOGSAVEDAYS', '"+DecodeUtil.EncryptBase64("7", dataGroup, true)+"', 1, '', 1, '2020-12-17 10:22:23', 'DEBUG日志存放天数', 'Logg配置', '0002');");
    	System.out.println("INSERT INTO `"+businessdb+"`.`base_sys_cnf`(`PKEY`, `PVAL`, `ENCRYPT`, `ENCRYPTCODE`, `STATE`, `UPDATETIME`, `CNFPARAMSDES`, `MODULENAME`, `MODULCODE`) VALUES ('DEBUGSQL', '"+DecodeUtil.EncryptBase64("1", dataGroup, true)+"', 1, '', 1, '2020-12-17 10:22:23', 'Sql打印开启模式', 'Debug配置', '0001');");
    	System.out.println("INSERT INTO `"+businessdb+"`.`base_sys_cnf`(`PKEY`, `PVAL`, `ENCRYPT`, `ENCRYPTCODE`, `STATE`, `UPDATETIME`, `CNFPARAMSDES`, `MODULENAME`, `MODULCODE`) VALUES ('ERRLOGPATH', '"+DecodeUtil.EncryptBase64("err", dataGroup, true)+"', 1, '', 1, '2020-12-17 10:22:23', '错误日志目录', 'Logg配置', '0002');");
    	System.out.println("INSERT INTO `"+businessdb+"`.`base_sys_cnf`(`PKEY`, `PVAL`, `ENCRYPT`, `ENCRYPTCODE`, `STATE`, `UPDATETIME`, `CNFPARAMSDES`, `MODULENAME`, `MODULCODE`) VALUES ('EXCEPTIONLOGPATH', '"+DecodeUtil.EncryptBase64("exception", dataGroup, true)+"', 1, '', 1, '2020-12-17 10:22:23', '异常日志目录', 'Logg配置', '0002');");
    	System.out.println("INSERT INTO `"+businessdb+"`.`base_sys_cnf`(`PKEY`, `PVAL`, `ENCRYPT`, `ENCRYPTCODE`, `STATE`, `UPDATETIME`, `CNFPARAMSDES`, `MODULENAME`, `MODULCODE`) VALUES ('ISCLOUDSEVER', '"+DecodeUtil.EncryptBase64("0", dataGroup, true)+"', 1, '', 1, '2020-12-17 10:22:23', '是否云端服务', '云台配置', '0003');");
    	System.out.println("INSERT INTO `"+businessdb+"`.`base_sys_cnf`(`PKEY`, `PVAL`, `ENCRYPT`, `ENCRYPTCODE`, `STATE`, `UPDATETIME`, `CNFPARAMSDES`, `MODULENAME`, `MODULCODE`) VALUES ('LOGLOOPMOD', '"+DecodeUtil.EncryptBase64("day", dataGroup, true)+"', 1, '', 1, '2020-12-17 10:22:23', '日志循环周期', 'Logg配置', '0002');");
    	System.out.println("INSERT INTO `"+businessdb+"`.`base_sys_cnf`(`PKEY`, `PVAL`, `ENCRYPT`, `ENCRYPTCODE`, `STATE`, `UPDATETIME`, `CNFPARAMSDES`, `MODULENAME`, `MODULCODE`) VALUES ('MQEYECLOUDIP', '"+DecodeUtil.EncryptBase64("121.196.184.133", dataGroup, true)+"', 1, '', 1, '2020-12-17 10:22:23', 'MQeye云台IP', '云台配置', '0003');");
    	System.out.println("INSERT INTO `"+businessdb+"`.`base_sys_cnf`(`PKEY`, `PVAL`, `ENCRYPT`, `ENCRYPTCODE`, `STATE`, `UPDATETIME`, `CNFPARAMSDES`, `MODULENAME`, `MODULCODE`) VALUES ('MQEYECLOUDPORT', '"+DecodeUtil.EncryptBase64("1024", dataGroup, true)+"', 1, '', 1, '2020-12-17 10:22:23', 'MQeye云台端口', '云台配置', '0005');");
    	System.out.println("INSERT INTO `"+businessdb+"`.`base_sys_cnf`(`PKEY`, `PVAL`, `ENCRYPT`, `ENCRYPTCODE`, `STATE`, `UPDATETIME`, `CNFPARAMSDES`, `MODULENAME`, `MODULCODE`) VALUES ('RUNPRO', '"+DecodeUtil.EncryptBase64("1", dataGroup, true)+"', 1, '', 1, '2020-12-17 10:22:23', '生产模式', 'Debug配置', '0001');");
    	System.out.println("INSERT INTO `"+businessdb+"`.`base_sys_cnf`(`PKEY`, `PVAL`, `ENCRYPT`, `ENCRYPTCODE`, `STATE`, `UPDATETIME`, `CNFPARAMSDES`, `MODULENAME`, `MODULCODE`) VALUES ('BUSINESSSCHEMA', '"+DecodeUtil.EncryptBase64(businessdb.toUpperCase(), dataGroup, true)+"', 1, '', 1, '2020-12-17 10:22:23', '主业务数据库名称', '系统配置', '0000');");
    	System.out.println("INSERT INTO `"+businessdb+"`.`base_sys_cnf`(`PKEY`, `PVAL`, `ENCRYPT`, `ENCRYPTCODE`, `STATE`, `UPDATETIME`, `CNFPARAMSDES`, `MODULENAME`, `MODULCODE`) VALUES ('SERVERDOMAIN', '"+DecodeUtil.EncryptBase64("1", dataGroup, true)+"', 1, '', 1, '2020-12-17 10:22:23', '服务端链接', '系统配置', '0000');");
    	System.out.println("INSERT INTO `"+businessdb+"`.`base_sys_cnf`(`PKEY`, `PVAL`, `ENCRYPT`, `ENCRYPTCODE`, `STATE`, `UPDATETIME`, `CNFPARAMSDES`, `MODULENAME`, `MODULCODE`) VALUES ('SQLLOGPATH', '"+DecodeUtil.EncryptBase64("sql", dataGroup, true)+"', 1, '', 1, '2020-12-17 10:22:23', 'SQL日志目录', 'Logg配置', '0002');");
    	System.out.println("INSERT INTO `"+businessdb+"`.`base_sys_cnf`(`PKEY`, `PVAL`, `ENCRYPT`, `ENCRYPTCODE`, `STATE`, `UPDATETIME`, `CNFPARAMSDES`, `MODULENAME`, `MODULCODE`) VALUES ('SUGGESTLOGPATH', '"+DecodeUtil.EncryptBase64("suggest", dataGroup, true)+"', 1, '', 1, '2020-12-17 10:22:23', '建议日志目录', 'Logg配置', '0002');");
    	System.out.println("INSERT INTO `"+businessdb+"`.`base_sys_cnf`(`PKEY`, `PVAL`, `ENCRYPT`, `ENCRYPTCODE`, `STATE`, `UPDATETIME`, `CNFPARAMSDES`, `MODULENAME`, `MODULCODE`) VALUES ('TOKENSAVETIME', '"+DecodeUtil.EncryptBase64("7200", dataGroup, true)+"', 1, '', 1, '2020-12-17 10:22:23', 'Token有效期', 'Token配置', '0004');");
    	System.out.println("INSERT INTO `"+businessdb+"`.`base_sys_cnf`(`PKEY`, `PVAL`, `ENCRYPT`, `ENCRYPTCODE`, `STATE`, `UPDATETIME`, `CNFPARAMSDES`, `MODULENAME`, `MODULCODE`) VALUES ('TOKENSAVETYPE', '"+DecodeUtil.EncryptBase64("DB", dataGroup, true)+"', 1, '', 1, '2020-12-17 10:22:23', 'Token存储方式', 'Token配置', '0004');");
    	System.out.println("INSERT INTO `"+businessdb+"`.`base_sys_cnf`(`PKEY`, `PVAL`, `ENCRYPT`, `ENCRYPTCODE`, `STATE`, `UPDATETIME`, `CNFPARAMSDES`, `MODULENAME`, `MODULCODE`) VALUES ('UCLOUD', '"+DecodeUtil.EncryptBase64("1", dataGroup, true)+"', 1, '', 1, '2020-12-17 10:22:23', '使用云端', '云台配置', '0003');");
    	System.out.println("INSERT INTO `"+businessdb+"`.`base_sys_cnf`(`PKEY`, `PVAL`, `ENCRYPT`, `ENCRYPTCODE`, `STATE`, `UPDATETIME`, `CNFPARAMSDES`, `MODULENAME`, `MODULCODE`) VALUES ('UMQEYECLOUD', '"+DecodeUtil.EncryptBase64("1", dataGroup, true)+"', 1, '', 1, '2020-12-17 10:22:23', '使用MQeye云台状态', '云台配置', '0003');");
    	System.out.println("INSERT INTO `"+businessdb+"`.`base_sys_cnf`(`PKEY`, `PVAL`, `ENCRYPT`, `ENCRYPTCODE`, `STATE`, `UPDATETIME`, `CNFPARAMSDES`, `MODULENAME`, `MODULCODE`) VALUES ('USEWSSSH', '"+DecodeUtil.EncryptBase64("1", dataGroup, true)+"', 1, '', 1, '2020-12-17 10:22:23', '是否使用SSH代理', 'SSH代理配置', '0000');");
    	System.out.println("INSERT INTO `"+businessdb+"`.`base_sys_cnf`(`PKEY`, `PVAL`, `ENCRYPT`, `ENCRYPTCODE`, `STATE`, `UPDATETIME`, `CNFPARAMSDES`, `MODULENAME`, `MODULCODE`) VALUES ('VERIFYLOCKERRTIMES', '"+DecodeUtil.EncryptBase64("5", dataGroup, true)+"', 1, '', 1, '2020-12-17 10:22:23', '账号密码连续错误锁定限制', '系统配置', '0000');");
    	System.out.println("INSERT INTO `"+businessdb+"`.`base_sys_cnf`(`PKEY`, `PVAL`, `ENCRYPT`, `ENCRYPTCODE`, `STATE`, `UPDATETIME`, `CNFPARAMSDES`, `MODULENAME`, `MODULCODE`) VALUES ('VERIFYSHOWERRTIMES', '"+DecodeUtil.EncryptBase64("3", dataGroup, true)+"', 1, '', 1, '2020-12-17 10:22:23', '账号密码连续错误验证码限制', '系统配置', '0000');");
    	System.out.println("INSERT INTO `"+businessdb+"`.`base_sys_cnf`(`PKEY`, `PVAL`, `ENCRYPT`, `ENCRYPTCODE`, `STATE`, `UPDATETIME`, `CNFPARAMSDES`, `MODULENAME`, `MODULCODE`) VALUES ('WARNLOGPATH', '"+DecodeUtil.EncryptBase64("warn", dataGroup, true)+"', 1, '', 1, '2020-12-17 10:22:23', '告警日志目录', 'Logg配置', '0002');");
    	System.out.println("INSERT INTO `"+businessdb+"`.`base_sys_cnf`(`PKEY`, `PVAL`, `ENCRYPT`, `ENCRYPTCODE`, `STATE`, `UPDATETIME`, `CNFPARAMSDES`, `MODULENAME`, `MODULCODE`) VALUES ('WSPORT', '"+DecodeUtil.EncryptBase64("6666", dataGroup, true)+"', 1, '', 1, '2020-12-17 10:22:23', 'WebSocket端口', '消息配置', '0005');");
    	System.out.println("INSERT INTO `"+businessdb+"`.`base_sys_cnf`(`PKEY`, `PVAL`, `ENCRYPT`, `ENCRYPTCODE`, `STATE`, `UPDATETIME`, `CNFPARAMSDES`, `MODULENAME`, `MODULCODE`) VALUES ('WSSSHPORT','"+DecodeUtil.EncryptBase64("6789", dataGroup, true)+"', 1, '', 1, '2020-12-17 10:22:23', 'SSHWebSocket端口', 'SSH代理配置', '0000');");
    	System.out.println("INSERT INTO `"+businessdb+"`.`base_sys_cnf`(`PKEY`, `PVAL`, `ENCRYPT`, `ENCRYPTCODE`, `STATE`, `UPDATETIME`, `CNFPARAMSDES`, `MODULENAME`, `MODULCODE`) VALUES ('WXAPIADRESS', '"+DecodeUtil.EncryptBase64("https://wx.iacyun.com/private/wx/api.data", dataGroup, true)+"', 1, '', 1, '2020-12-17 10:22:23', '微信相关请求地址', '云台配置', '0005');");
    	System.out.println("INSERT INTO `"+businessdb+"`.`base_sys_cnf`(`PKEY`, `PVAL`, `ENCRYPT`, `ENCRYPTCODE`, `STATE`, `UPDATETIME`, `CNFPARAMSDES`, `MODULENAME`, `MODULCODE`) VALUES ('WXSERVER', '"+DecodeUtil.EncryptBase64("0", dataGroup, true)+"', 1, '', 1, '2020-12-17 10:22:23', '是否微信服务器', '云台配置', '0005');");
    	System.out.println("-- 插入业务系统");
    	System.out.println("INSERT INTO `"+basedb+"`.`sys_platform` (`platformcode`, `platformname`, `platformsname`, `platformalias`, `platformicon`, `platformoper`, `platformstate`, `platformurl`, `platformdecript`, `platformorder`, `defaulturl`, `datagroup`, `platformdomain`, `iconname`) VALUES('P_0001','"+groupName+"','"+groupName+"','MQ-EduSys','ios-school','superadmin','1','','','1','','"+dataGroup+"','/MQ-EduSys-home','ios-school');");
    	System.out.println("-- 初始化业务级别系统资源");
    	
    	System.out.println("-- 插入业务角色");
    	System.out.println("INSERT INTO `"+basedb+"`.`sys_role` (`roleid`, `name`, `type`, `location`, `descript`, `creater`, `creattime`, `creatunitid`, `datagroup`, `platformcode`) values('0002','管理员角色','0','0','管理员角色','superadmin','2020-10-30 18:43:54','','"+dataGroup+"','');");
    	System.out.println("INSERT INTO `"+basedb+"`.`sys_role` (`roleid`, `name`, `type`, `location`, `descript`, `creater`, `creattime`, `creatunitid`, `datagroup`, `platformcode`) values('0010','公用角色','0','0','公用角色默认角色','superadmin','2020-10-30 18:43:54','','"+dataGroup+"','');");
    	System.out.println("-- 插入业务级别Module信息");
    	
    	System.out.println("-- 给超管赋予全部角色");
    	System.out.println("INSERT INTO `"+basedb+"`.`sys_roleresource` (roleid, resourceid, state, creater, createtime, datagroup) SELECT '0001' AS roleid,indexno AS resourceid ,0 AS state ,'superadmin' AS creater ,'"+DateUtil.getCurDateTime()+"' AS createtime , '"+dataGroup+"' AS datagroup  FROM `"+basedb+"`.`sys_resource` ;");
	}
	
}
